### PR TITLE
Silence warnings when building ODE and zlib

### PR DESCRIPTION
**Pull request by davecamp**
Hi,

A small PR that will silence warnings when building zlib and ODE.

### CODE REVIEW

**Comment by davecamp** [comment]
Hold fire on this PR for the moment. I tried this on MacOs and it worked ok. It doesn't play nicely with the msvc compiler. I'll see about fixing it up and report back.

**Comment by kfprimm** [comment]
Yep, `BB_MSVC` is fine.

Also, I'm wondering why GitHub Actions didn't fire and run the build/tests. Can you try changing [this line](https://github.com/blitz3d-ng/package/blob/master/.github/workflows/ci.yml#L2) to:

```yaml
on:
  - push
  - pull_request
```

and see if it triggers?

**Comment by kfprimm** [comment]
@davecamp, great thanks. I think there's been a change to Actions that I need to address. master failed yesterday as well. I will try to get this resolve today or tomorrow.

**Comment by davecamp** [comment]
@kfprimm 
Do the checks not pass due to an issue with the autobuild? or was something I did that's not compatible with all supported targets?

**Comment by kfprimm** [comment]
Something changed upstream with the GitHub Actions runners and the required kernel sounds modules are no longer available on the ubuntu-20.04 images. I've switched to ubuntu-20.04 and things are functioning again.

Merge master into your branch and things should build correctly.

**Comment by davecamp** [comment]
Ahh I understand. Looks like you have it sorted now. Well done !

**Comment by kfprimm** [comment]
Ok @davecamp, one more time! Merge master and hopefully that should be it.

I appreciate your patience. This is the first PR since all the new CI stuff was implemented.

**Comment by davecamp** [comment]
@kfprimm 
Hey, no worries!
I don't mind helping out at all. I have confidence that you'll get it fixed up - all in good time 👍

**Comment by kfprimm** [comment]
Ok, once more. 

I properly tested with a PR this time.

**Pull request merged**
